[package]
name = "basic-client"
version = "0.1.0"
authors = ["Nathan Miller <Nathan.Miller@wdc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus = "0.8.1"

